objects/Book_Store__c.object
<CustomObject>
    <fields>
        <fullName>ContactPhone__c</fullName>
        <label>ContactPhone</label>
        <type>Phone</type>
    </fields>
    <label>Book Store</label>
    <nameField>
        <label>Book Store  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BookStoreItemController.cls
public class BookStoreItemController {
    
    public final Book_Store__c BookStore {get; set;}

    public BookStoreItemController() {
        BookStore = [SELECT Id, Name, ContactPhone__c FROM Book_Store__c 
                   WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
    }

    public PageReference back(){
        PageReference Page = new PageReference('/BookStoreMap');
        Page.setRedirect(true);
        return Page;
    }
}